import fs from "node:fs/promises";
import path from "node:path";
import { computeProjectState } from "../project/project-state";
import { replaceAutoSection } from "./markers";

export type DocsSyncInput = { projectRoot: string; profile?: string };

async function readOrEmpty(p: string) {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return "";
  }
}

async function writeEnsured(p: string, content: string) {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, content, "utf8");
}

async function listDirFilesOneLevel(dirPath: string) {
  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile())
      .map((e) => e.name)
      .filter((n) => !n.toLowerCase().endsWith(".md"))
      .slice(0, 50);
  } catch {
    return [];
  }
}

export async function runDocsSync(input: DocsSyncInput) {
  const state = await computeProjectState(input.projectRoot, input.profile ?? "core");
  const inv = [
    "## Inventory",
    "",
    `- Profile (computed): \`${state.appliedProfile}\``,
    `- Modules: \`${JSON.stringify(state.modules)}\``,
    "",
    "### Routes (detected)",
    ...state.routes.slice(0, 200).map((r) => `- \`${r.kind}\` ${r.path}`),
  ].join("\n");

  const prdPath = path.join(input.projectRoot, "PRD.md");
  const archPath = path.join(input.projectRoot, "ARCHITECTURE.md");
  const erdPath = path.join(input.projectRoot, "ERD.md");

  const prd = replaceAutoSection(await readOrEmpty(prdPath), inv);
  const arch = replaceAutoSection(await readOrEmpty(archPath), inv);
  const erdPrev = await readOrEmpty(erdPath);

  // ERD: best-effort parse from Drizzle SQL migrations (tables + FKs).
  async function buildErdFromMigrations() {
    const migDir = path.join(input.projectRoot, "drizzle", "migrations");
    let entries: string[] = [];
    try {
      entries = (await fs.readdir(migDir)).filter((f) => f.endsWith(".sql"));
    } catch {
      entries = [];
    }
    const sqls = await Promise.all(entries.map((f) => readOrEmpty(path.join(migDir, f))));
    const sql = sqls.join("\n\n");
    const tables: Record<string, { cols: string[]; fks: string[] }> = {};

    // CREATE TABLE "name" ( ... );
    const createRe = /create table\s+"?([a-zA-Z0-9_]+)"?\s*\(([\s\S]*?)\);\s*/gi;
    let m: RegExpExecArray | null;
    while ((m = createRe.exec(sql))) {
      const name = m[1];
      const body = m[2];
      const cols = body
        .split(/\r?\n/)
        .map((l) => l.trim())
        .filter((l) => !!l && !l.toLowerCase().startsWith("constraint"))
        .map((l) => l.replace(/,$/, ""));
      tables[name] = tables[name] ?? { cols: [], fks: [] };
      tables[name].cols = cols;
    }

    // ALTER TABLE "a" ADD CONSTRAINT ... FOREIGN KEY ("x") REFERENCES "b"("y")
    const fkRe =
      /alter table\s+"?([a-zA-Z0-9_]+)"?\s+add constraint\s+"?([a-zA-Z0-9_]+)"?\s+foreign key\s*\("?([a-zA-Z0-9_]+)"?\)\s+references\s+"?([a-zA-Z0-9_]+)"?\s*\("?([a-zA-Z0-9_]+)"?\)/gi;
    while ((m = fkRe.exec(sql))) {
      const fromT = m[1];
      const fromC = m[3];
      const toT = m[4];
      const toC = m[5];
      tables[fromT] = tables[fromT] ?? { cols: [], fks: [] };
      tables[fromT].fks.push(`${fromT}.${fromC} -> ${toT}.${toC}`);
    }

    const lines: string[] = [];
    lines.push("## Entities");
    lines.push("");
    const names = Object.keys(tables).sort();
    if (names.length === 0) {
      lines.push("- (no migrations detected yet)");
      return lines.join("\n");
    }
    for (const t of names) {
      lines.push(`### \`${t}\``);
      lines.push("");
      const cols = tables[t].cols.length ? tables[t].cols : ["(columns not detected)"];
      lines.push("**Columns**");
      lines.push("");
      lines.push(...cols.map((c) => `- \`${c}\``));
      if (tables[t].fks.length) {
        lines.push("");
        lines.push("**Relations (FKs)**");
        lines.push("");
        lines.push(...tables[t].fks.map((x) => `- \`${x}\``));
      }
      lines.push("");
    }
    return lines.join("\n").trimEnd();
  }

  const erdBody = await buildErdFromMigrations();
  const erd = replaceAutoSection(erdPrev, [inv, "", erdBody].join("\n"));

  await writeEnsured(prdPath, prd || `# PRD\n\n${inv}\n`);
  await writeEnsured(archPath, arch || `# ARCHITECTURE\n\n${inv}\n`);
  await writeEnsured(erdPath, erd || `# ERD\n\n${inv}\n`);

  // Root README.md (PRD-equivalent, barebones but complete)
  const readmePath = path.join(input.projectRoot, "README.md");
  const isCreateNextReadme = (s: string) =>
    s.includes("bootstrapped with [`create-next-app`]") || s.includes("This is a [Next.js]");
  const readmeAuto = [
    `# ${state.config.app.name}`,
    "",
    "Production-ready Next.js App Router starter generated by `0xstack`.",
    "",
    "## What you get",
    "- Flat repo layout (no `src/`, no route groups) with all non-`app/` code in `lib/`",
    "- Better Auth (text IDs), Drizzle ORM (Postgres), tiered architecture (repos -> services -> actions/loaders -> UI)",
    "- Internal writes via Server Actions; external integrations via versioned HTTP API routes (`/api/v1/*`)",
    "",
    "## Modules (enabled)",
    `- Configured profile: \`${state.appliedProfile}\``,
    `- Modules: \`${JSON.stringify(state.modules)}\``,
    "",
    "## Commands",
    "Run these from the repo root:",
    "",
    "```bash",
    "pnpm dev",
    "pnpm lint",
    "pnpm typecheck",
    "```",
    "",
    "### 0xstack maintenance commands",
    "```bash",
    "# baseline: enforce schema, generate Better Auth tables, create migrations, activate modules",
    "npx 0xstack baseline --profile core",
    "",
    "# doctor: validate architecture boundaries + env + required files",
    "npx 0xstack doctor --profile core",
    "",
    "# docs sync: regenerate inventories + subsystem READMEs",
    "npx 0xstack docs-sync",
    "```",
    "",
    "pnpm alternative:",
    "```bash",
    "pnpm dlx 0xstack baseline --profile core",
    "pnpm dlx 0xstack doctor --profile core",
    "pnpm dlx 0xstack docs-sync",
    "```",
    "",
    "## Environment variables",
    "- Copy `.env.example` → `.env.local` and fill required keys.",
    "- Core validation lives in `lib/env/schema.ts` (plus module env schemas in `lib/env/*`).",
    "",
    "## Architecture (quick map)",
    "- `lib/db/*`: Drizzle schema + DB client",
    "- `lib/repos/*`: DB reads/writes (no HTTP, no UI)",
    "- `lib/services/*`: business logic + permissions, calls repos",
    "- `lib/actions/*`: server actions for internal UI flows (calls services)",
    "- `lib/loaders/*`: cached read models (calls services/loaders)",
    "- `app/api/v1/*`: external HTTP routes (calls services, never repos directly)",
    "",
    "## Routes (detected)",
    ...state.routes.slice(0, 200).map((r) => `- \`${r.kind}\` ${r.path}`),
    "",
  ].join("\n");
  const prevReadme = await readOrEmpty(readmePath);
  const base = !prevReadme || isCreateNextReadme(prevReadme) ? "" : prevReadme;
  await writeEnsured(readmePath, replaceAutoSection(base, readmeAuto));

  // Subsystem READMEs (enterprise baseline)
  const subsystems = [
    "actions",
    "auth",
    "billing",
    "content",
    "db",
    "env",
    "hooks",
    "hooks/client",
    "loaders",
    "mutation-keys",
    "query-keys",
    "repos",
    "rules",
    "seo",
    "services",
    "storage",
    "stores",
    "security",
  ];
  for (const sub of subsystems) {
    const p = path.join(input.projectRoot, "lib", sub, "README.md");
    const dirPath = path.join(input.projectRoot, "lib", sub);
    const files = await listDirFilesOneLevel(dirPath);
    const entrypoints = files.length
      ? ["## Entry points (detected)", "", ...files.map((f) => `- \`${f}\``), ""].join("\n")
      : "## Entry points (detected)\n\n- (none detected)\n";
    const body = [
      `# \`lib/${sub}\``,
      "",
      "## Purpose",
      "- (auto) Describe what this subsystem owns.",
      "",
      "## Allowed imports",
      "- (auto) Define allowed layers and forbidden dependencies.",
      "",
      entrypoints.trimEnd(),
      "",
      "## Conventions",
      "- (auto) Naming + patterns.",
      "",
      "## Examples",
      "- Prefer `services/*` from routes; avoid importing repos from `app/`.",
      "- Keep rules in `lib/rules/*` and validate inputs at boundaries.",
      "",
    ].join("\n");
    const prev = await readOrEmpty(p);
    await writeEnsured(p, replaceAutoSection(prev || "", body));
  }
}

