import fs from "node:fs/promises";
import path from "node:path";
import { computeProjectState } from "../project/project-state";
import { replaceAutoSection } from "./markers";

export type DocsSyncInput = { projectRoot: string };

async function readOrEmpty(p: string) {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return "";
  }
}

async function writeEnsured(p: string, content: string) {
  await fs.mkdir(path.dirname(p), { recursive: true });
  await fs.writeFile(p, content, "utf8");
}

async function listDirFilesOneLevel(dirPath: string) {
  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    return entries
      .filter((e) => e.isFile())
      .map((e) => e.name)
      .filter((n) => !n.toLowerCase().endsWith(".md"))
      .slice(0, 50);
  } catch {
    return [];
  }
}

export async function runDocsSync(input: DocsSyncInput) {
  const state = await computeProjectState(input.projectRoot, "minimal");
  const inv = [
    "## Inventory",
    "",
    `- Profile (computed): \`${state.appliedProfile}\``,
    `- Modules: \`${JSON.stringify(state.modules)}\``,
    "",
    "### Routes (detected)",
    ...state.routes.slice(0, 200).map((r) => `- \`${r.kind}\` ${r.path}`),
  ].join("\n");

  const prdPath = path.join(input.projectRoot, "PRD.md");
  const archPath = path.join(input.projectRoot, "ARCHITECTURE.md");
  const erdPath = path.join(input.projectRoot, "ERD.md");

  const prd = replaceAutoSection(await readOrEmpty(prdPath), inv);
  const arch = replaceAutoSection(await readOrEmpty(archPath), inv);
  const erd = replaceAutoSection(await readOrEmpty(erdPath), inv);

  await writeEnsured(prdPath, prd || `# PRD\n\n${inv}\n`);
  await writeEnsured(archPath, arch || `# ARCHITECTURE\n\n${inv}\n`);
  await writeEnsured(erdPath, erd || `# ERD\n\n${inv}\n`);

  // Root README.md (PRD-equivalent, barebones but complete)
  const readmePath = path.join(input.projectRoot, "README.md");
  const isCreateNextReadme = (s: string) =>
    s.includes("bootstrapped with [`create-next-app`]") || s.includes("This is a [Next.js]");
  const readmeAuto = [
    `# ${state.config.app.name}`,
    "",
    "Production-ready Next.js App Router starter generated by `0xstack`.",
    "",
    "## What you get",
    "- Flat repo layout (no `src/`, no route groups) with all non-`app/` code in `lib/`",
    "- Better Auth (text IDs), Drizzle ORM (Postgres), tiered architecture (repos -> services -> actions/loaders -> UI)",
    "- Internal writes via Server Actions; external integrations via versioned HTTP API routes (`/api/v1/*`)",
    "",
    "## Modules (enabled)",
    `- Configured profile: \`${state.appliedProfile}\``,
    `- Modules: \`${JSON.stringify(state.modules)}\``,
    "",
    "## Commands",
    "Run these from the repo root:",
    "",
    "```bash",
    "pnpm dev",
    "pnpm lint",
    "pnpm typecheck",
    "```",
    "",
    "### 0xstack maintenance commands",
    "```bash",
    "# baseline: enforce schema, generate Better Auth tables, create migrations, activate modules",
    "npx 0xstack baseline --profile minimal",
    "",
    "# doctor: validate architecture boundaries + env + required files",
    "npx 0xstack doctor --profile minimal",
    "",
    "# docs sync: regenerate inventories + subsystem READMEs",
    "npx 0xstack docs-sync",
    "```",
    "",
    "pnpm alternative:",
    "```bash",
    "pnpm dlx 0xstack baseline --profile minimal",
    "pnpm dlx 0xstack doctor --profile minimal",
    "pnpm dlx 0xstack docs-sync",
    "```",
    "",
    "## Environment variables",
    "- Copy `.env.example` → `.env.local` and fill required keys.",
    "- Core validation lives in `lib/env/schema.ts` (plus module env schemas in `lib/env/*`).",
    "",
    "## Architecture (quick map)",
    "- `lib/db/*`: Drizzle schema + DB client",
    "- `lib/repos/*`: DB reads/writes (no HTTP, no UI)",
    "- `lib/services/*`: business logic + permissions, calls repos",
    "- `lib/actions/*`: server actions for internal UI flows (calls services)",
    "- `lib/loaders/*`: cached read models (calls services/loaders)",
    "- `app/api/v1/*`: external HTTP routes (calls services, never repos directly)",
    "",
    "## Routes (detected)",
    ...state.routes.slice(0, 200).map((r) => `- \`${r.kind}\` ${r.path}`),
    "",
  ].join("\n");
  const prevReadme = await readOrEmpty(readmePath);
  const base = !prevReadme || isCreateNextReadme(prevReadme) ? "" : prevReadme;
  await writeEnsured(readmePath, replaceAutoSection(base, readmeAuto));

  // Subsystem READMEs (enterprise baseline)
  const subsystems = [
    "actions",
    "auth",
    "billing",
    "content",
    "db",
    "env",
    "hooks",
    "hooks/client",
    "loaders",
    "mutation-keys",
    "query-keys",
    "repos",
    "rules",
    "seo",
    "services",
    "storage",
    "stores",
    "security",
  ];
  for (const sub of subsystems) {
    const p = path.join(input.projectRoot, "lib", sub, "README.md");
    const dirPath = path.join(input.projectRoot, "lib", sub);
    const files = await listDirFilesOneLevel(dirPath);
    const entrypoints = files.length
      ? ["## Entry points (detected)", "", ...files.map((f) => `- \`${f}\``), ""].join("\n")
      : "## Entry points (detected)\n\n- (none detected)\n";
    const body = [
      `# \`lib/${sub}\``,
      "",
      "## Purpose",
      "- (auto) Describe what this subsystem owns.",
      "",
      "## Allowed imports",
      "- (auto) Define allowed layers and forbidden dependencies.",
      "",
      entrypoints.trimEnd(),
      "",
      "## Conventions",
      "- (auto) Naming + patterns.",
      "",
      "## Examples",
      "- Prefer `services/*` from routes; avoid importing repos from `app/`.",
      "- Keep rules in `lib/rules/*` and validate inputs at boundaries.",
      "",
    ].join("\n");
    const prev = await readOrEmpty(p);
    await writeEnsured(p, replaceAutoSection(prev || "", body));
  }
}

