import path from "node:path";
import fs from "node:fs/promises";
import { backupAndRemove, ensureDir, writeFileEnsured } from "./fs-utils";
import type { Module } from "./types";

export const seoModule: Module = {
  id: "seo",
  install: async () => {},
  activate: async (ctx) => {
    if (!ctx.modules.seo) {
      await backupAndRemove(ctx.projectRoot, "app/robots.ts");
      await backupAndRemove(ctx.projectRoot, "app/sitemap.ts");
      await backupAndRemove(ctx.projectRoot, "app/opengraph-image.tsx");
      await backupAndRemove(ctx.projectRoot, "app/twitter-image.tsx");
      await backupAndRemove(ctx.projectRoot, "lib/seo/jsonld.ts");
      return;
    }

    await ensureDir(path.join(ctx.projectRoot, "lib", "seo"));
    await writeFileEnsured(
      path.join(ctx.projectRoot, "lib", "seo", "jsonld.ts"),
      `export function safeJsonLd<T>(data: T): string {
  return JSON.stringify(data).replace(/</g, "\\\\u003c");
}
`
    );
    await writeFileEnsured(
      path.join(ctx.projectRoot, "app", "robots.ts"),
      `import type { MetadataRoute } from "next";
import { env } from "@/lib/env/server";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: "*", allow: "/" }],
    sitemap: \`\${env.NEXT_PUBLIC_APP_URL}/sitemap.xml\`,
  };
}
`
    );
    await writeFileEnsured(
      path.join(ctx.projectRoot, "app", "sitemap.ts"),
      `import type { MetadataRoute } from "next";
import { listPosts } from "@/lib/loaders/blog.loader";

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const base: MetadataRoute.Sitemap = [
    { url: "/", lastModified: new Date() },
    { url: "/about", lastModified: new Date() },
    { url: "/contact", lastModified: new Date() },
    { url: "/pricing", lastModified: new Date() },
    { url: "/terms", lastModified: new Date() },
    { url: "/privacy", lastModified: new Date() },
    { url: "/login", lastModified: new Date() },
    { url: "/get-started", lastModified: new Date() },
  ];

  // Optional blog
  try {
    const posts = await listPosts();
    for (const p of posts) {
      if (!p.published) continue;
      base.push({ url: \`/blog/\${p.slug}\`, lastModified: new Date(p.date || Date.now()) });
    }
    base.push({ url: "/blog", lastModified: new Date() });
  } catch {
    // blog disabled or loader missing
  }

  return base;
}
`
    );

    // Social images (basic, but production-valid)
    await writeFileEnsured(
      path.join(ctx.projectRoot, "app", "opengraph-image.tsx"),
      `import { ImageResponse } from "next/og";

export const runtime = "edge";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: 64,
          background: "#0a0a0a",
          color: "#ffffff",
        }}
      >
        <div style={{ fontSize: 56, fontWeight: 800, lineHeight: 1.05 }}>0xmilord</div>
        <div style={{ marginTop: 16, fontSize: 28, color: "#d4d4d4" }}>Production-ready starter</div>
      </div>
    ),
    size
  );
}
`
    );
    await writeFileEnsured(
      path.join(ctx.projectRoot, "app", "twitter-image.tsx"),
      `export { default, size, contentType, runtime } from "./opengraph-image";\n`
    );

    // Patch root metadata defaults if still create-next-app template.
    const layoutPath = path.join(ctx.projectRoot, "app", "layout.tsx");
    const layoutSrc = await fs.readFile(layoutPath, "utf8").catch(() => "");
    if (layoutSrc && layoutSrc.includes('title: "Create Next App"')) {
      const next = layoutSrc.replace(
        /export const metadata: Metadata = \{\s*title: "Create Next App",\s*description: "Generated by create next app",\s*\};/m,
        `export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000"),
  title: { default: process.env.NEXT_PUBLIC_APP_NAME ?? "0xmilord", template: "%s · " + (process.env.NEXT_PUBLIC_APP_NAME ?? "0xmilord") },
  description: "Production-ready Next.js starter.",
  openGraph: { type: "website", title: process.env.NEXT_PUBLIC_APP_NAME ?? "0xmilord" },
  twitter: { card: "summary_large_image", title: process.env.NEXT_PUBLIC_APP_NAME ?? "0xmilord" },
};`
      );
      await fs.writeFile(layoutPath, next, "utf8");
    }
  },
  validate: async () => {},
  sync: async () => {},
};

